let watchId = null;
const query = new URLSearchParams(location.search);
if (query.get('addr')) document.getElementById('addr').value = query.get('addr');
if (query.get('port')) document.getElementById('port').value = query.get('port');
let tailcatConn = null, connecting = null, responseBuffer = new Uint8Array(0), sending = false;
const wasmReady = (async()=>{const go=new Go();let result;try{result=await WebAssembly.instantiateStreaming(fetch('tailcat.wasm'),go.importObject)}catch(e){const r=await fetch('tailcat.wasm');result=await WebAssembly.instantiate(await r.arrayBuffer(),go.importObject)}go.run(result.instance);for(let i=0;i<100;i++){if(window.tailcatDial)return;await new Promise(r=>setTimeout(r,100))}throw new Error('Tailcat WASM 준비 시간 초과')})();
const status = t => document.getElementById('s').textContent = t;
async function getConnection(){await wasmReady;if(tailcatConn)return tailcatConn;if(connecting)return connecting;connecting=tailcatDial({addr:document.getElementById('addr').value.trim(),port:Number(document.getElementById('port').value)||8787,derpMapURL:'https://tailcat.dev/derpmap.json'}).then(c=>{tailcatConn=c;responseBuffer=new Uint8Array(0);return c}).finally(()=>{connecting=null});return connecting}
function appendBytes(a,b){const x=new Uint8Array(a.length+b.length);x.set(a);x.set(b,a.length);return x}
async function readResponse(conn){const decoder=new TextDecoder();while(true){const marker=responseBuffer.indexOf(13);if(marker>=0&&responseBuffer[marker+1]===10&&responseBuffer[marker+2]===13&&responseBuffer[marker+3]===10){const head=decoder.decode(responseBuffer.slice(0,marker));const m=/\r\nContent-Length:\s*(\d+)/i.exec(head);const length=m?Number(m[1]):0;const total=marker+4+length;while(responseBuffer.length<total){const chunk=await conn.read();if(chunk===null)throw new Error('Tailcat 연결 종료');responseBuffer=appendBytes(responseBuffer,chunk)}responseBuffer=responseBuffer.slice(total);return}}
  const chunk=await conn.read();if(chunk===null)throw new Error('Tailcat 연결 종료');responseBuffer=appendBytes(responseBuffer,chunk)}
async function sendLocation(p){if(sending)return;sending=true;try{const c=p.coords,body=JSON.stringify({lat:c.latitude,lon:c.longitude,altitude:c.altitude||0,speed:c.speed||0,heading:c.heading||0,accuracy:c.accuracy||10}),bytes=new TextEncoder().encode(body),conn=await getConnection();const req=`POST /api/location HTTP/1.1\r\nHost: mockgps\r\nContent-Type: application/json\r\nContent-Length: ${bytes.length}\r\nConnection: keep-alive\r\n\r\n${body}`;await conn.write(new TextEncoder().encode(req));await readResponse(conn);lat.textContent=c.latitude.toFixed(6);lon.textContent=c.longitude.toFixed(6);status('전송 중 · '+new Date().toLocaleTimeString())}catch(e){if(tailcatConn){tailcatConn.close();tailcatConn=null}status('재연결 중…')}finally{sending=false}}
function start(){ if(!addr.value.trim()) return status('Tailcat 주소를 입력하세요.'); if(!navigator.geolocation) return status('이 브라우저는 GPS를 지원하지 않습니다.'); watchId=navigator.geolocation.watchPosition(sendLocation,e=>status('GPS 오류: '+e.message),{enableHighAccuracy:true,maximumAge:0,timeout:5000}); status('GPS 권한을 기다리는 중…'); }
function stop(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;if(tailcatConn){tailcatConn.close();tailcatConn=null}status('중지됨');}
